### ISSUE TITLE
レース情報の多重登録

### ISSUE THREAD

**Issue by musicsoul0142** [amate/UmaUmaCruise#1]
シニア級1月後半のG3 根岸ステークスが二つ登録されている。
「根岸ステークス」と「根岸S」の二つが存在しています。
RaceDataLibrary.jsonの最後尾に「根岸S」が記述されている。

![3c7ac6c135ed7e0628496f548ff9afea 1](https://user-images.githubusercontent.com/54382718/115210730-dbeecc00-a139-11eb-8694-906d61f0b321.png)

**Comment by mayopon** [comment]
> シニア級1月後半のG3 根岸ステークスが二つ登録されている。

> RaceDataLibrary.jsonの最後尾に「根岸S」が記述されている。

v1.4でも1248行目辺りと1545行目辺りの2つ存在しているようです。
