### ISSUE TITLE
【要望】UmaMusumeLibrary.jsonについて

### ISSUE THREAD

**Issue by sonicshadow** [amate/UmaUmaCruise#100]
１週年アップデート後イベント選択肢データの精度が低い
・仕様変更後のサポカートイベント更新してない（重要）
・キタサンブラックのイベント抜ける
データの参考元を変更希望します

**Comment by amate** [comment]
>１週年アップデート後イベント選択肢データの精度が低い 
> ・仕様変更後のサポカートイベント更新してない（重要） 
> ・キタサンブラックのイベント抜ける
どのイベントが存在しない、もしくは変更されているのかを知らせてくれれば修正します
それかUmaMusumeLibraryModify.jsonを修正してプルリクエストを送ってください

>データの参考元を変更希望します
別の参照先で許可を得られるかどうか分かりませんし
手元のスクレイピングスクリプトを修正するのが面倒なので変更はしません
