### ISSUE TITLE
更新されたイベント内容が反映されない

### ISSUE THREAD

**Issue by shimao0324** [amate/UmaUmaCruise#102]
gamerchのwikiを修正したので、UmaMusumeLibrary.jsonの更新版が配布されました。
しかし、UmaUmaCruise上では更新されたイベント内容が表示されません。
UmaLibraryフォルダの中のJsonファイルを開き、該当のイベントを検索したところ、
1:UmaMusumeLibrary.json
2:UmaMusumeLibrary_prev.json
3:UmaMusumeLibraryOrigin.json
4:UmaMusumeLibraryRevision.json
の4ファイル内に該当のイベントの記載があり、1だけが更新後のイベント内容になっていました。

どこをどう修正したら正しい内容が反映されるかお教えください。
また、各jsonファイルの内容？利用方法？についての記載が見つかりませんでした。ありかを教えてください。

![ユキノビジン](https://user-images.githubusercontent.com/46845940/158809137-6ff0f788-9d73-4442-b50c-f81aeac24559.jpg)

**Comment by amate** [comment]
UmaMusumeLibraryRevision.jsonにある該当イベントを削除してください

**Comment by shimao0324** [comment]
正しく表示されました。ありがとうございました。
