### ISSUE TITLE
【不具合】マルゼンスキー育成イベント「お任せハンドル」未認識

### ISSUE THREAD

**Issue by L-SMK** [amate/UmaUmaCruise#107]
![screenshot_1651836201](https://user-images.githubusercontent.com/26026130/167122382-da0d93a4-60e3-4385-8227-a93eeb993567.png)

育成ウマ娘「【フォーミュラオブルージュ】マルゼンスキー」では未認識
育成ウマ娘「【ぶっとび☆さまーナイト】マルゼンスキー」では認識された

**Comment by amate** [comment]
修正しました
