### ISSUE TITLE
[bug]スタートを押すとエラーメッセージが出ずに強制終了する

### ISSUE THREAD

**Issue by Kenty0079** [amate/UmaUmaCruise#11]
ウマ娘を起動時にumaumacruiseのスタートを押すといきなりクラッシュします。
環境はWindows10 home 64bit 20H2、umaumacruiseのバージョンは1.2です。
管理者として実行・ウイルスソフトの除外設定等を試したり、
置くフォルダを　C:\UmaUmaCruise　にしてもだめでした。

**Comment by BlackEllis** [comment]
同様の現象かはわかりませんが、似たような事象で動きませんでした。
`Tesseract`(tessdata/jpn.traineddata) の文字認識ファイルを下記のいずれかに置き換えて動くようになりました。
- [通常版](https://github.com/tesseract-ocr/tessdata/blob/master/jpn.traineddata)
- [FAST版](https://github.com/tesseract-ocr/tessdata_fast/blob/master/jpn.traineddata)

※ あくまで私の環境での暫定対処ですので、同一現象化はわからないで。。。

**Comment by Kenty0079** [comment]
FAST版の方で無事動作するようになりました！ありがとうございます！
