### ISSUE TITLE
Win11への対応について

### ISSUE THREAD

**Issue by JUDECKA** [amate/UmaUmaCruise#110]
いつもお世話になっております。
先日ウマウマクルーズが入っているPCをWin10（21H2）からWin11にアップグレードしたのですが、
タイトルバーに「ウマ娘のウィンドウが見つかりません」と表示され、
ウマ選択や選択肢がリンクしないようになってしまいました。
環境依存なのかどうか不明ですが、対応状況等確認させていただけますでしょうか。

**Comment by amate** [comment]
windows11の環境がないので分かりませんが
UmaUmaCruise.exeを管理者権限で実行してみてください

**Comment by JUDECKA** [comment]
ご回答ありがとうございます。動作確認できました。
