### ISSUE TITLE
ウオッカのイベント「究極の2択」が認識されない

### ISSUE THREAD

**Issue by ossan-pg** [amate/UmaUmaCruise#111]
ウオッカの育成イベント「究極の2択」が認識されません。
GamerchのWikiにも当該イベントが記載されてないのでそれが原因かと思います。

![image](https://user-images.githubusercontent.com/7059614/171393010-36051c25-5b95-4bb2-8825-646ac5659309.png)

**Comment by amate** [comment]
修正しました
