### ISSUE TITLE
[質問] Ver1.20での動作に関して

### ISSUE THREAD

**Issue by JE892354** [amate/UmaUmaCruise#116]
いつも更新ありがとうございます！ウマウマクルーズありがたく使用させていただいております。

現在Ver1.20で【Flare】アストンマーチャンでUmaUmaCruiseが正常に動作しません。
詳細画面を開いても識別できず、手動でマーチャンを選択した上で選択肢が出てきても認識しません。
管理者権限起動、ドライブ直下収納、更新確認で2022-11-29の最新状態、3種の取り込み方式は試してみました。

![screenshot_1670231713](https://user-images.githubusercontent.com/119848884/205599430-0de48171-45ad-4d96-9274-75ce0b677335.png)
![screenshot_1670230437](https://user-images.githubusercontent.com/119848884/205599442-41cc16ce-ca5b-4f4a-9aec-797beddeab88.png)

**Comment by amate** [comment]
修正しました
設定から"UmaMusumeLibrary.jsonの更新確認"を実行してください
