### ISSUE TITLE
SRエルコンドルパサーのイベントでtypo

### ISSUE THREAD

**Issue by ponsfoot** [amate/UmaUmaCruise#117]
［泥まみれのコンパネーロ］エルコンドルパサーのイベント"情熱的に、うららかに！"の効果に誤字があります。
"パワー全開泥んこプロレス！"の効果で体力は「-10」です。
よろしくおねがいします。

![log](https://user-images.githubusercontent.com/1582952/206119744-4c54d219-ba56-4c95-83b3-21b8f2b30f31.jpg)
![typo](https://user-images.githubusercontent.com/1582952/206119760-7b917d4c-5362-4475-9e7a-25ba99202af0.jpg)

**Comment by amate** [comment]
修正しました
設定から"UmaMusumeLibrary.jsonの更新確認"を実行してください
