### ISSUE TITLE
イベント未認識

### ISSUE THREAD

**Issue by ponsfoot** [amate/UmaUmaCruise#118]
イベント未認識です。
[めんこいめんこいむつのはな]ユキノビジン「丸い誘惑」
よろしくおねがいします。

![yukino](https://user-images.githubusercontent.com/1582952/206428655-72544b5e-d5b7-407c-a854-63b8903658d1.jpg)

**Comment by amate** [comment]
修正しました
設定から"UmaMusumeLibrary.jsonの更新確認"を実行してください
