### ISSUE TITLE
イベント未認識

### ISSUE THREAD

**Issue by ponsfoot** [amate/UmaUmaCruise#119]
イベント未認識です。
[めんこいめんこいむつのはな]ユキノビジン「イマドキ♪お出かけコース」
(UmaUmaCruise の方はこれの前のイベントのままです)
よろしくおねがいします。

![yukino2](https://user-images.githubusercontent.com/1582952/206433938-932cfe8c-73d4-499f-95a5-08c1eb8b0f10.jpg)

**Comment by amate** [comment]
修正しました
設定から"UmaMusumeLibrary.jsonの更新確認"を実行してください
