### ISSUE TITLE
グラスワンダー：「おつかいは人のためならず」が認識されない

### ISSUE THREAD

**Issue by L-SMK** [amate/UmaUmaCruise#12]
![image](https://user-images.githubusercontent.com/26026130/115576329-5d8f5700-a2fe-11eb-8619-5a2538003232.png)

![image](https://user-images.githubusercontent.com/26026130/115576377-66802880-a2fe-11eb-9e6d-405678241197.png)

読み取りは「おつかいは人のためならず」となっているが、
ソース：［迫る熱に押されて］キタサンブラック
イベント名：情けは人のためならず
が優先して表示されてしまっています。

**Comment by L-SMK** [comment]
誤字修正
誤「おつかいは人のためにならず」→正「おつかいは人のためならず」

**Comment by amate** [comment]
v1.3で修正されたはずです
もし直ってなかったらまたissueを立ててください
その場合は、本体の"スクリーンショット"で保存した画像を上げてもらえると助かります
