### ISSUE TITLE
イベント未認識([稲荷所縁江戸紫]イナリワン)

### ISSUE THREAD

**Issue by ponsfoot** [amate/UmaUmaCruise#120]
[稲荷所縁江戸紫]イナリワンのイベント「怒涛の恩返しラッシュ」が未認識です。
よろしくおねがいします。
![missingevent](https://user-images.githubusercontent.com/1582952/209339406-bb882d19-dd68-4cc7-a907-025c06dde70c.jpg)

**Comment by amate** [comment]
修正しました
設定から"UmaMusumeLibrary.jsonの更新確認"を実行してください
