### ISSUE TITLE
イベント効果の不足([パリピ・ぱーりないと！]ダイタクヘリオス)

### ISSUE THREAD

**Issue by ponsfoot** [amate/UmaUmaCruise#121]
[パリピ・ぱーりないと！]ダイタクヘリオスのイベント「#lol #Party!! #2nd」において、上の選択肢を選んだときに成功・失敗判定があります。
失敗の場合は添付画像のとおりです。
よろしくおねがいします。
![lolparty](https://user-images.githubusercontent.com/1582952/209459662-70d71766-9636-4d7d-b249-df44600df196.jpg)

**Comment by amate** [comment]
修正しました
設定から"UmaMusumeLibrary.jsonの更新確認"を実行してください
