### ISSUE TITLE
イベント効果の不足([レッドストライフ]ゴールドシップ)

### ISSUE THREAD

**Issue by ponsfoot** [amate/UmaUmaCruise#122]
[レッドストライフ]ゴールドシップの育成イベント「翌日そろってしわがれ声」での上選択時の結果の情報が不足しています。
よろしくおねがいします。
![golshi](https://user-images.githubusercontent.com/1582952/209553486-5a5bdfa1-bf28-44ad-818f-4e17c7fb8b8f.jpg)

**Comment by amate** [comment]
修正しました
設定から"UmaMusumeLibrary.jsonの更新確認"を実行してください
