### ISSUE TITLE
イベント未認識([めんこいめんこいむつのはな]ユキノビジン)

### ISSUE THREAD

**Issue by ponsfoot** [amate/UmaUmaCruise#123]
[めんこいめんこいむつのはな]ユキノビジンの育成イベント「初詣」の認識がうまく行っていないようです。
よろしくおねがいします。
![newyear](https://user-images.githubusercontent.com/1582952/210044148-a66a0443-8bdb-4783-8826-36efcf81617c.jpg)

**Comment by ponsfoot** [comment]
オプションを選択したあとに表示されました。
![afterchoose](https://user-images.githubusercontent.com/1582952/210044367-0a14b42f-f7b9-4123-8bfc-98a4fb40e5c2.jpg)

**Comment by amate** [comment]
修正しました
設定から"UmaMusumeLibrary.jsonの更新確認"を実行してください
