### ISSUE TITLE
イベント認識失敗([Heroic Author]ゼンノロブロイ)

### ISSUE THREAD

**Issue by ponsfoot** [amate/UmaUmaCruise#126]
ゼンノロブロイのイベント「初詣」において、イベントの認識に失敗する(すごく時間がかかる)ようです。スクショを撮ったあと続けようと思ったら認識していました。
よろしくおねがいします。
![robroy_newyear](https://user-images.githubusercontent.com/1582952/211018937-adb7da78-2ff3-4a82-846e-4d16a3c23437.jpg)

**Comment by amate** [comment]
修正しました
設定から"UmaMusumeLibrary.jsonの更新確認"を実行してください
