### ISSUE TITLE
イベント未認識(【Heroic Author】ゼンノロブロイ)

### ISSUE THREAD

**Issue by ponsfoot** [amate/UmaUmaCruise#127]
ゼンノロブロイの育成(おでかけ)イベント「ちょっとの背伸び」を認識しないようです。
よろしくおねがいします。
![robroy](https://user-images.githubusercontent.com/1582952/213165376-71007db1-59f1-4b74-abc3-21ca4ca69b8e.jpg)

**Comment by amate** [comment]
修正しました
