### ISSUE TITLE
誤認識 ：【ぱんぱかティルトット】マチカネタンホイザ

### ISSUE THREAD

**Issue by Kan-nana** [amate/UmaUmaCruise#128]
マチカネタンホイザの育成イベント「追加の自主トレ」が誤認識されるみたいです。
よろしくおねがいします。
![bandicam 2023-01-26 03-58-18-862](https://user-images.githubusercontent.com/123587931/214662380-a7eff498-0cb6-4190-bcab-dd3c7e929f4f.png)

**Comment by amate** [comment]
修正しました
設定から"UmaMusumeLibrary.jsonの更新確認"を実行してください
