### ISSUE TITLE
イベント情報不足(［Hands up,crook!］タイキシャトル)

### ISSUE THREAD

**Issue by ponsfoot** [amate/UmaUmaCruise#129]
［Hands up,crook!］タイキシャトルの連続イベント「教訓之二:決して撮影を諦めるな」において、「演技の才能もあるんだな！」を選んだときの成功時の情報が不足しているようです。
よろしくおねがいします。
![ssrtaiki](https://user-images.githubusercontent.com/1582952/215242636-49beffb7-8e04-49ee-96b1-7471b42273e1.jpg)

**Comment by amate** [comment]
修正しました
設定から"UmaMusumeLibrary.jsonの更新確認"を実行してください
