### ISSUE TITLE
イベント情報不足(【エレガンス・ライン】メジロマックイーン)

### ISSUE THREAD

**Issue by ponsfoot** [amate/UmaUmaCruise#130]
【エレガンス・ライン】メジロマックイーン育成イベント「レース場グルメの誘惑」において3つ目の選択肢の情報が不足しているようです。
よろしくおねがいします。
![mcqueen](https://user-images.githubusercontent.com/1582952/215242782-3196fef6-83c8-40d7-820c-7b55e8a5feff.jpg)

**Comment by amate** [comment]
修正しました
設定から"UmaMusumeLibrary.jsonの更新確認"を実行してください
