### ISSUE TITLE
イベント未認識(デッド･エンド【通せん坊】ジャングルポケット)

### ISSUE THREAD

**Issue by toridaihuku** [amate/UmaUmaCruise#132]
ジャングルポケットSRサポートカードの各種イベントが認識されないようです、確認お願い致します。
![screenshot_1681811699](https://user-images.githubusercontent.com/131154855/232745275-53704aa7-c253-420e-85e2-cf004961ea6d.png)
![e6f2eaf9456f544735d6134bd78324b8](https://user-images.githubusercontent.com/131154855/232745344-df1ffa2a-c666-44ca-bafb-0c2a39af8fcd.jpg)

**Comment by amate** [comment]
修正しました
設定から"UmaMusumeLibrary.jsonの更新確認"を実行してください
