### ISSUE TITLE
イベント未認識　ヤマニンゼファー　やさしい俄風

### ISSUE THREAD

**Issue by beyonzs** [amate/UmaUmaCruise#133]
ヤマニンゼファーの固有イベント　やさしい俄風　が、認識できないようです
よろしくお願いします。
![RS10s001792](https://user-images.githubusercontent.com/122301618/234852827-67453200-6335-4783-a62c-71e63a9024ff.png)
![screenshot_1682595586](https://user-images.githubusercontent.com/122301618/234852838-48861889-ee2d-49dd-aa5d-156f8448a092.png)

**Comment by amate** [comment]
修正しました
設定から"UmaMusumeLibrary.jsonの更新確認"を実行してください
