### ISSUE TITLE
トウカイテイオー：「"女帝"vs."帝王"」が認識されない

### ISSUE THREAD

**Issue by oppipp** [amate/UmaUmaCruise#14]
トウカイテイオー：「"女帝"vs."帝王"」が認識されない
![スクリーンショット 2021-04-23 002423](https://user-images.githubusercontent.com/41785525/115740951-45850980-a3ca-11eb-9685-a8a9599e67fd.png)

**Comment by amate** [comment]
v1.3で修正されたはずです
もし直ってなかったらまたissueを立ててください
その場合は、本体の"スクリーンショット"で保存した画像を上げてもらえると助かります
