### ISSUE TITLE
アプリケーションエラーで落ちました

### ISSUE THREAD

**Issue by JUDECKA** [amate/UmaUmaCruise#18]
お疲れ様です。

実行後に何も応答なかったのでイベントログを確認したところ、下記のエラーが検出されました。

障害が発生しているアプリケーション名: UmaUmaCruise.exe、バージョン: 1.0.0.1、タイム スタンプ: 0x607ee444
障害が発生しているモジュール名: ucrtbase.dll、バージョン: 10.0.19041.789、タイム スタンプ: 0x2bd748bf
例外コード: 0xc0000409
障害オフセット: 0x000000000007286e
障害が発生しているプロセス ID: 0x40c4
障害が発生しているアプリケーションの開始時刻: 0x01d7382c6d8c15f1
障害が発生しているアプリケーション パス: C:\Program Files (x86)\UmaUmaCruise\UmaUmaCruise.exe
障害が発生しているモジュール パス: C:\WINDOWS\System32\ucrtbase.dll
レポート ID: c705a409-4d0d-41c4-b52c-f629e54f6e7f
障害が発生しているパッケージの完全な名前: 
障害が発生しているパッケージに関連するアプリケーション ID

実行環境はx64 Windows10Pro 20H2です。
VC++のモジュールが呼び出されていたので、一応MSサイトから落としてかけ直したのですが同様でした（上記のエラー）。

お手数ですが対応できればよろしくお願いいたします。

**Comment by amate** [comment]
v1.3で修正しました

**Comment by JUDECKA** [comment]
正常動作確認しました。
迅速な対応感謝いたします。
