### ISSUE TITLE
ウオッカ：「共に極めよ、カッコ良さの道」が誤認識される 

### ISSUE THREAD

**Issue by oppipp** [amate/UmaUmaCruise#19]
ウオッカ：「共に極めよ、カッコ良さの道」が誤認識される 
OCR状全く問題ないのでDB周りの問題かと
![スクリーンショット 2021-04-24 015426](https://user-images.githubusercontent.com/41785525/115904710-0fb25480-a4a0-11eb-93fe-3e310d9a087d.png)

**Comment by amate** [comment]
v1.3で修正されたはずです
もし直ってなかったらまたissueを立ててください
その場合は、本体の"スクリーンショット"で保存した画像を上げてもらえると助かります
