### ISSUE TITLE
ウィンドウ範囲の取得

### ISSUE THREAD

**Issue by T3600** [amate/UmaUmaCruise#2]
ウィンドウ範囲の取得にバグがあるようです
それとも解像度に指定があるのでしょうか？
![1033002202](https://user-images.githubusercontent.com/82808591/115215400-6c2f1000-a13e-11eb-9873-0aa86ab24cab.jpg)
![2210330002](https://user-images.githubusercontent.com/82808591/115215750-c3cd7b80-a13e-11eb-8f99-444b797514f3.jpg)

**Comment by pimpapimpa** [comment]
自分も同じような現象になっており利用ができません。
解像度は2560×1440です。
お手数をおかけいたしますがよろしくお願いします。

**Comment by tarusake** [comment]
ただの利用者ですが、暫定的に回避できましたので、情報共有いたします。

・UmaUmaCuirse.exeを右クリックし「プロパティ」をクリック
・「互換性」タブをクリックし、「高DPI設定の変更」を選択
・「高いDPIスケールの動作を上書きします。」にチェックを入れます
・拡大縮小の実行元：「アプリケーション」を選択します
・OKをクリックしてウィンドウを閉じます

![image](https://user-images.githubusercontent.com/12277051/115227924-13ff0a80-a14c-11eb-9524-07a72e9e2a51.png)
![image](https://user-images.githubusercontent.com/12277051/115228118-558fb580-a14c-11eb-8256-17e3ffdb476d.png)

**Comment by amate** [comment]
v1.2で修正
それでもまだ動作しないようでしたらまたissueをお願いします
