### ISSUE TITLE
v1.2で日付の認識制度が低下している

### ISSUE THREAD

**Issue by WabisabiNeet** [amate/UmaUmaCruise#20]
日付のキャプチャ範囲がずれているためOCRの精度が低下しています。
![image](https://user-images.githubusercontent.com/38955440/115904513-d37ef400-a49f-11eb-802f-9c2ec41d9d3e.png)

https://github.com/amate/UmaUmaCruise/blob/master/UmaLibrary/Common.json#L22
CurrentTurnBoundsのy座標を40くらいにすれば精度は改善します。

ただ、v1.2更新後からキャプチャ範囲が少し下にずれているため、おそらくこちらが根本原因と思われます。
(githubの背景が白だとわかりづらいですがスクショの上端に白帯がある)
![screenshot_1619196859](https://user-images.githubusercontent.com/38955440/115904678-045f2900-a4a0-11eb-8791-1188a5b3834a.png)

**Comment by amate** [comment]
v1.4で修正しました
