### ISSUE TITLE
グラスワンダー：「譲れないこと」の選択肢が逆

### ISSUE THREAD

**Issue by mino-s2000** [amate/UmaUmaCruise#21]
v1.2を使用中。1.3で修正済みであれば取り消してください。

現状：
緑→行ってらっしゃい！
黄色→トラブルに巻き込まれたら危ない

実際：
緑→トラブルに巻き込まれたら危ない
黄色→行ってらっしゃい！

**Comment by amate** [comment]
v1.4で修正しました
