### ISSUE TITLE
文字コードをutf8でビルド出来るようにして欲しい

### ISSUE THREAD

**Issue by laycnc** [amate/UmaUmaCruise#22]
VC++でutf8でビルドをする為にはC/C++ コンパイラのオプションに、"/source-charset:utf-8"を追加する事で
ソースコードをutf8としてビルドする事が出来ます。
文字化けの原因にもなりますので対応をして欲しいです

参考リンク: http://tech.hikware.com/article/20171020a.html

また、テキストエディタ側に文字コードをutf8と認識させる為にeditorconfigという設定ファイルの追加もして欲しいです。
VisualStudioはデフォルトでeditorconfigに対応していますのでファイルを追加するだけで対応は出来るかと思います

参考リンク:https://qiita.com/naru0504/items/82f09881abaf3f4dc171

**Comment by amate** [comment]
最新のコミットで対応
