### ISSUE TITLE
win7でのエラー

### ISSUE THREAD

**Issue by s-hamu** [amate/UmaUmaCruise#23]
win7で当exeダブルクリック直後に以下の記述があるダイアログが表示され、アプリの起動できません。
（v1.3、v1.2どちらも同様です）
「UmaUmaCruise.exe エントリポイントが見つかりません
プロシージャエントリポイント SetThreadDpiAwarenessContextがダイナミックライブラリ　USER32.dllから見つかりませんでした」

**Comment by amate** [comment]
v1.4で修正しました

**Comment by s-hamu** [comment]
起動するようになりました＆win7で2～3時間ほど使っていましたが何の問題もなく動いています。
想像通り凄く便利なツールですね。即座に対応して頂いて本当にありがとうございました。
