### ISSUE TITLE
ビルド手順の簡略化

### ISSUE THREAD

**Issue by nachume** [amate/UmaUmaCruise#26]
要求ライブラリの内、WTL以外はCMakeを使わずにvcpkgだけて完結できるのでreadmeより少し簡略化できそうです

- vcpkgでopencv+contrib+tesseract-ocrの一括インストール
https://qiita.com/RivaleDgg/items/0462882296ad6d658e2e
上記手順のインストールのコマンドはvcpkg install opencv4[text,world]:x64-windowsに変更する
- boostのインストール
vcpkg install boost:x64-windows
- JSON for Modern C++のインストール
vcpkg install nlohmann-json:x64-windows
- vcpkgとVisual Studioの統合
vcpkg integrate install
これにより$(SolutionDir)opencv/と$(SolutionDir)/tesseractは不要
- WTLの準備
https://sourceforge.net/projects/wtl/
をDLし任意のフォルダに展開する
インクルードディレクトリにWTLのパスを追加する
- プロジェクトプロパティ→リンカー→入力→追加の依存ファイルのファイル名を変更する
(Debug) opencv_world451d.lib → opencv_worldd.lib
(Release) opencv_world451.lib → opencv_world.lib

**Comment by amate** [comment]
最新のコミットで対応
