### ISSUE TITLE
イベント誤認識 「ダンスレッスン」

### ISSUE THREAD

**Issue by shishi** [amate/UmaUmaCruise#27]
他キャラクターでも同様にシンボリルドルフのダンスレッスンが出てしまうことを確認しました。

![image](https://user-images.githubusercontent.com/341746/116196390-65bc1c00-a76e-11eb-8edf-805af7dde01b.png)
![screenshot_1619505365](https://user-images.githubusercontent.com/341746/116196395-68b70c80-a76e-11eb-87d8-a249ae8a08ec.png)

**Comment by amate** [comment]
こちらの環境では再現せず
コンボボックスで設定した育成ウマ娘以外のイベントが出ることはないはずなんですが…

**Comment by Kaiay** [comment]
日本語下手ですすみません
この前似たような状況があるので報告します
①育成始める前で因子継承で別のウマ娘の詳細見る時ツールが自動的に育成ウマ娘が選択されます
②間違った育成ウマ娘変えずに育成を始め　イベント「ダンスレッスン」出る
③ツールの育成ウマ娘が間違ったことが分かった　←この時点正しい育成ウマ娘に換えっても　間違った育成ウマ娘のイベント「ダンスレッスン」が表示されるまま

**Comment by amate** [comment]
・v1.11で育成ウマ娘選択画面から育成ウマ娘を引っ張ってくるようにしたので、大丈夫になったはず
