### ISSUE TITLE
[bug]サポートカード「サイレンススズカ(SSR)」イベント名「どうすれば」の選択肢がおかしい

### ISSUE THREAD

**Issue by oppipp** [amate/UmaUmaCruise#29]
v1.4にて確認
ゲームの方では2択なのにツール側では3択になっている。
![screenshot_1619515449](https://user-images.githubusercontent.com/41785525/116218847-ea666480-a785-11eb-8dd7-4b7ce249c8d0.png)
![タイトルなし](https://user-images.githubusercontent.com/41785525/116219016-18e43f80-a786-11eb-93e4-1f85c1a19ae5.png)

**Comment by musicsoul0142** [comment]
本イベントは二択ですが、2番目と3番目の選択肢はランダム発生（どちらかのみが選ばれる）ので、今の状態で間違いないです。 https://gamewith.jp/uma-musume/article/show/257459

**Comment by amate** [comment]
Rサポートの方のイベントが出てしまっているようなのですが、実害がないので修正しません。
