### ISSUE TITLE
イベント「相応しくない自分」より「相応しい自分」が優先されて表示される

### ISSUE THREAD

**Issue by niratama** [amate/UmaUmaCruise#3]
ライスシャワーの育成ウマ娘イベント「相応しくない自分」の選択肢で似た名前の「相応しい自分」のデータが表示されてしまっています。

![umaumacruise1](https://user-images.githubusercontent.com/141543/115216970-f9bf2f80-a13f-11eb-99a9-f7064de2f33b.png)

Aboutダイアログのdebug機能でのOCR結果では正しく認識できていて、しばらく放置しているとごくたまに正常に認識されますが、主に「相応しい自分」のデータが優先されているようです。

![umaumacruise2](https://user-images.githubusercontent.com/141543/115216996-00e63d80-a140-11eb-9cb0-c49cad0f2ab1.png)

**Comment by amate** [comment]
v1.3で修正されたはずです
もし直ってなかったらまたissueを立ててください
その場合は、本体の"スクリーンショット"で保存した画像を上げてもらえると助かります
