### ISSUE TITLE
Readme通り 「デバッグの開始」 を実行すると、Debug Assertion Failed!が表示され実行に失敗する

### ISSUE THREAD

**Issue by tori-08** [amate/UmaUmaCruise#36]
制作感謝です。対応・回答いただけたらありがたいです

v1.6（master）をプルしてReadmeを頼りに実行してみましたが、Debug Assertion Failed! ウィンドウが表示されます

しっかりとコードを読んではいませんが、UmaMusumeLibrary.jsonが読み込めてないっぽいので、生成されたUmaumaCruise/x64/Debug/UmaCruise.exeを、UmaumaCruise/にコピーすると実行はできましたが、スタートボタン押下後でまた別のエラーがでました

Path：C:\Users\fuji\UmaUmaCruise
OS：Windows 10 Pro 64Bit 20H2 19042.928

下記に「デバッグの開始」 を実行したあとのログを貼ります

`'UmaCruise.exe' (Win32): 'C:\Users\fuji\UmaUmaCruise\x64\Debug\UmaCruise.exe' が読み込まれました。シンボルが読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\ntdll.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\kernel32.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\KernelBase.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\user32.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\win32u.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\gdi32.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\gdi32full.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\msvcp_win.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\ucrtbase.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\advapi32.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\msvcrt.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\sechost.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\rpcrt4.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\shell32.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\ole32.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\combase.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\oleaut32.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\shlwapi.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\ws2_32.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\winmm.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\comdlg32.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.928_none_faefac437613c6cc\GdiPlus.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.844_none_ca00b6081b84eb1d\comctl32.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\SHCore.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\winhttp.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.844_none_ca00b6081b84eb1d\comctl32.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.844_none_ca00b6081b84eb1d\comctl32.dll' がアンロードされました
'UmaCruise.exe' (Win32): 'C:\Windows\System32\imm32.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\kernel.appcore.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\bcryptprimitives.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\uxtheme.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\msctf.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\OnDemandConnRouteHelper.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\OnDemandConnRouteHelper.dll' がアンロードされました
'UmaCruise.exe' (Win32): 'C:\Windows\System32\atlthunk.dll' が読み込まれました。
Debug Assertion Failed!

Program: C:\Users\fuji\UmaUmaCruise\x64\Debug\UmaCruise.exe
File: C:\Users\fuji\UmaUmaCruise\UmaCruise\UmaEventLibrary.cpp
Line: 118

Expression: ifs

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)
'UmaCruise.exe' (Win32): 'C:\Windows\System32\TextShaping.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\TextInputFramework.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\CoreUIComponents.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\CoreMessaging.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\WinTypes.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\ntmarta.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\WinTypes.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\WinTypes.dll' がアンロードされました
'UmaCruise.exe' (Win32): 'C:\Windows\System32\clbcatq.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Program Files (x86)\Google\Google Japanese Input\GoogleIMEJaTIP64.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\input.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\dbghelp.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\d2d1.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\DWrite.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\userenv.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\windows.storage.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\wldp.dll' が読み込まれました。
'UmaCruise.exe' (Win32): 'C:\Windows\System32\profapi.dll' が読み込まれました。
スレッド 0x31c はコード 3 (0x3) で終了しました。
スレッド 0x1bf8 はコード 3 (0x3) で終了しました。
スレッド 0x3a04 はコード 3 (0x3) で終了しました。
スレッド 0x20cc はコード 3 (0x3) で終了しました。
プログラム '[2408] UmaCruise.exe' はコード 3 (0x3) で終了しました。`

**Comment by amate** [comment]
https://github.com/amate/UmaUmaCruise/releases/download/v1.6/UmaUmaCruise_1.6.zip
上記ファイルに入ってるUmaLibraryとtessdataを
C:\Users\fuji\UmaUmaCruise\x64\Debug\
フォルダにコピーしてください

**Comment by tori-08** [comment]
@amate 動作確認できました、早速のご対応ありがとうございます
個人での開発大変かと思いますが、ほどほどに頑張ってください！
