### ISSUE TITLE
[要望] レース一覧をカレンダー表示してほしい

### ISSUE THREAD

**Issue by todcxtr** [amate/UmaUmaCruise#37]
レース一覧ですが、画像のようにカレンダーのように表示することってできないでしょうか。
今の一覧ですと現在から何か月後に目標レースがあるのか…というのが分かりづらく感じます。
また9月以降のようなレースが多くある期間の場合、1ヶ月分しかレースが表示されず、何度もスクロールして確認することもあります。

![image](https://user-images.githubusercontent.com/1488469/116978626-efd02b80-acfe-11eb-996a-6901435b92b9.png)
前半、後半は月の中で背景色を変えて表現しています。
ジュニア・クラシック・シニアは左端の列で表現しています。(Jr, Cl, Se)

レース場、左右の方向、根幹/非根幹についても芝/ダのように出せればいいとは思いますが、レース当日に分かればいいかな…と思いこのサンプルでは出していません。
レースにカーソルを合わせたときにツールチップとしてレースの情報が表示できればいいと思います。

もちろん大変な変更だと思うので、お好みでなかったり無理と判断されたらCloseしていただいて構いません。

**Comment by amate** [comment]
さすがにこれをGDIで実装するのは大変なので、すみません…
