### ISSUE TITLE
イベント誤認識「"女帝"と"帝王"」

### ISSUE THREAD

**Issue by shishi** [amate/UmaUmaCruise#38]
おそらくは 「"女帝"と"帝王"」というイベント名なのに `UmaMusumeLibrary.json` 内では「女帝と帝王」というイベント名になっていることが原因かと思いました。

![screenshot_1620139479](https://user-images.githubusercontent.com/341746/117022157-f7a9c300-ad32-11eb-9cf0-980d328582be.png)
![image](https://user-images.githubusercontent.com/341746/117022197-009a9480-ad33-11eb-8795-b58da910a9d5.png)

**Comment by amate** [comment]
v1.7で修正しました
