### ISSUE TITLE
イベント誤認識

### ISSUE THREAD

**Issue by sina2** [amate/UmaUmaCruise#39]
![screenshot_1620195729](https://user-images.githubusercontent.com/3647788/117103816-ff5e7b80-adb5-11eb-8a55-62a88d045db1.png)
![無題](https://user-images.githubusercontent.com/3647788/117103852-143b0f00-adb6-11eb-88ed-c91bbbf4c72a.png)

**Comment by amate** [comment]
v1.7で修正しました
