### ISSUE TITLE
イベント「オペレーション：オーダー遂行」より「オペレーション：補習」が優先表示される

### ISSUE THREAD

**Issue by 3nukit** [amate/UmaUmaCruise#4]
ミホノブルボンの育成ウマ娘イベント「オペレーション：オーダー遂行」より「オペレーション：補習」が優先されて表示されてしまいます。
![image](https://user-images.githubusercontent.com/42205954/115225141-b2896c80-a148-11eb-9332-92bd30aa6a65.png)

**Comment by 3nukit** [comment]
「オペレーション：外出時トラブル」でも同現象が発生します。

まだイベントを確認できていませんが
・「オペレーション：ダンスフィーバー」
・「オペレーション：エンジョイ縁日」
でも同現象が発生するかと思われます。
![image](https://user-images.githubusercontent.com/42205954/115227195-1f9e0180-a14b-11eb-9a46-99d2cd867175.png)

**Comment by amate** [comment]
v1.3で修正されたはずです
もし直ってなかったらまたissueを立ててください
その場合は、本体の"スクリーンショット"で保存した画像を上げてもらえると助かります
