### ISSUE TITLE
イベント無認識　ゴールドシップ「夏合宿(3年目)終了」

### ISSUE THREAD

**Issue by AyuAyuWorld** [amate/UmaUmaCruise#40]
v1.6にて、
ゴールドシップのイベント「夏合宿(3年目)終了」が認識されません。
![screenshot_1620230650](https://user-images.githubusercontent.com/83718595/117173269-9142a480-ae07-11eb-958c-a8e41ed1c10f.png)
![無認識](https://user-images.githubusercontent.com/83718595/117173284-94d62b80-ae07-11eb-8243-d3cdc4c80271.png)

※「UmaUmaCruise」のSSは「夏合宿(3年目)終了」選択肢表示時に
　アプリを再起動し撮影した際のものです。
　アプリを閉じる前は直前イベントの選択肢が残った状態で表示されていました。

**Comment by amate** [comment]
v1.7で修正しました
