### ISSUE TITLE
テーマの選択

### ISSUE THREAD

**Issue by poponta1218** [amate/UmaUmaCruise#41]
ダークテーマが追加されましたが私の環境ではダークテーマが自動で選択されてしまうため，テーマを手動で変更できるようにしていただきたいです．

また，設定からUmaUmaCruiseのディレクトリを開けるようにすることは出来るのでしょうか．

**Comment by pachi0084** [comment]
UmaLibrary ディレクトリー内にあるCommon.jsonをテキストエディタなどで開きます。

85行目に"Theme"という文字列があるので
"Dark"はダークモード時の色テーマ
"Light"は通常時の色テーマ
を表しています。

Lightの文字をDarkに変え、LightをDarkに変えることで、擬似的にテーマの変更ができます。

設定を実装されるのを希望の場合は実装されるまでお待ちください。

![WS000176](https://user-images.githubusercontent.com/3452465/117312002-af6bdb80-aebf-11eb-8678-7b82f5c434dc.jpg)

**Comment by poponta1218** [comment]
ご返信ありがとうございます．
当方もその方法を試していたのですが以下の画像のようにカラーコードを設定できる箇所以外の部分がどうしてもダークテーマに引っ張られてしまいます．
これはおそらく私の環境の設定に依存しているのだと思いますが．
![image](https://user-images.githubusercontent.com/34686350/117448214-6f692f00-af79-11eb-8657-db91acc53d5c.png)
![image](https://user-images.githubusercontent.com/34686350/117448608-ea324a00-af79-11eb-9f56-6216a13a254b.png)
ご指摘ありがとうございました．

**Comment by amate** [comment]
v1.8でテーマ選択機能を追加
