### ISSUE TITLE
育成ウマ娘（ゴールドシップ）イベントを認識しない

### ISSUE THREAD

**Issue by erica333** [amate/UmaUmaCruise#42]
OS：Windows10 Pro 64bit
UmaUmaCruiseバージョン：1.7
umamusumeバージョン：1.2.10

UmaUmaCruise、umamusume共に再起動を行いましたが表示されませんでした。
他のイベントは問題なく表示されました。

![スクリーンショット 2021-05-06 14 15 16](https://user-images.githubusercontent.com/83746277/117245251-7e66b900-ae75-11eb-88d6-e2bf040b5ff6.png)
![screenshot_1620277605](https://user-images.githubusercontent.com/83746277/117245261-8292d680-ae75-11eb-844e-bc08cfa46c49.png)

**Comment by TamaZooo** [comment]
相乗り失礼します。
ゴルシのG1で2着のレース入着が認識出来ていないので併せて対応お願いします。

![image](https://user-images.githubusercontent.com/43776206/117474332-cb41b100-af95-11eb-89a9-6c9964d57812.png)

**Comment by amate** [comment]
v1.8で修正したつもり
