### ISSUE TITLE
[千紫万紅にまぎれぬ一凛]グラスワンダーの「文殿、思ひ煩ふ」が認識されない

### ISSUE THREAD

**Issue by trium-v** [amate/UmaUmaCruise#43]
OS：Windows10 Pro 64bit
UmaUmaCruiseバージョン：1.7
umamusumeバージョン：1.2.10

UmaumaCruise、umamusume共に再起動等試しましたが、表示されませんでした。
他のイベントは問題なく表示されております。
EventnameBoundsにて確認したところ、イベント名が正常に認識されていないのかなと思いました。
![screenshot_1620320101](https://user-images.githubusercontent.com/83779447/117336844-9e2ec900-aed7-11eb-8fda-60fb53a82630.png)

**Comment by amate** [comment]
ウィンドウサイズが小さすぎて文字を認識できていないようです
ウィンドウを大きくするか、
UmaLibrary内にあるCommon.jsonの
"MinThreshold": 0.40
とあるのを
"MinThreshold": 0.20
などに変更してみてください
