### ISSUE TITLE
Auto selection not working

### ISSUE THREAD

**Issue by terry3041** [amate/UmaUmaCruise#44]
![Code_pCTIjZtDdh](https://user-images.githubusercontent.com/19218518/117406698-fdc0bf00-af3f-11eb-891a-c7468caac0a9.png)
I have set all the text bound correctly but auto selecting horse is not working for me.
Detecting event works fine though.
Here is my [Common.json](https://gist.github.com/terry3041/f3c10bdb665185ba3a987d9698774146)
Any idea?

**Comment by amate** [comment]
The text color is used to get the Uma-Musume name.
The DMM version and the emulator output different colors, so the name could not be obtained.

Try rewriting HSV_TextColorBounds in Common.json as follows

```
            "HSV_TextColorBounds": [
                [0, 16],
                [0, 255],
                [0, 190]
            ]
```

**Comment by terry3041** [comment]
It works now.
Thank you so much!
