### ISSUE TITLE
【要望】レース一覧にトロフィーの取得状況を管理できる機能を実装してほしい

### ISSUE THREAD

**Issue by AyuAyuWorld** [amate/UmaUmaCruise#45]
レース一覧にトロフィーの取得状況を管理できる機能を実装していただくことは可能でしょうか？

トロフィー未取得のレースに対してレース予約するでもいいのですが、
予約はウマ娘毎の保存となるため、
トロフィーの取得状況管理としては使いにくいです。

案としては
・レース一覧内にチェックボックス型の項目を一つ追加していただき、ユーザーが手動で入力する
・任意のレースに予約時とは別の着色ができるようにする
ぐらいしか思いつきませんが、
全ウマ娘共通で参照できる管理機能があれば嬉しいです。

お忙しいところ恐れ入りますが、
ご検討いただけないでしょうか。

**Comment by amate** [comment]
そういうのは別にスプレッドシートやエクセルで管理すればいいと思うので
すみません…
