### ISSUE TITLE
【要望】レース一覧にファン数を反映して欲しい

### ISSUE THREAD

**Issue by TamaZooo** [amate/UmaUmaCruise#47]
どのレースでどれくらいファン数を稼げるかシミュレートしたいので実装出来ないか？

・カラムにファン数欄を追加
・ファン数はゲーム内の+何人でもよい
・レース予約を入れた合計獲得ファン数をURA予想の上あたりに表示
・URA予選/準決勝/決勝で獲得出来るファン数も上記合計獲得ファン数に加算

**Comment by pachi0084** [comment]
あなたが知り得たいことは、「Umamusume Trainer's Clipboard」というWebページを使うことで得られます。

編成するサポートカードのファン数ボーナスによって獲得ファン数が変わる仕様のため正確な数字は得られませんので当Webページを使うのが無難だと思われます。

**Comment by TamaZooo** [comment]
ありがとうございます。
このようなサイトがあったのですね！助かります。
