### ISSUE TITLE
【question】what type of software license is this project?

### ISSUE THREAD

**Issue by RyoLee** [amate/UmaUmaCruise#49]
thx 4 ur gd works!

**Comment by amate** [comment]
Use of the source code is prohibited except for personal use.

**Comment by RyoLee** [comment]
> Use of the source code is prohibited except for personal use.

so CAN(OR SHOULD？) I open source code(and publish binary files) after doing some customizations like
https://github.com/RyoLee/UmaUmaCruise/commit/8efd21aabc071ca14dfa7687ade6a4a08ae611b7

**Comment by amate** [comment]
I can give you special permission for this level of change.
UmaUmaCruise is software that interferes with other companies' games, and we have set strict limits to prevent **misuse** of the source code.
Please understand this in advance.

**Comment by RyoLee** [comment]
> I can give you special permission for this level of change.
> UmaUmaCruise is software that interferes with other companies' games, and we have set strict limits to prevent **misuse** of the source code.
> Please understand this in advance.

thx! have a nice day
