### ISSUE TITLE
☆2スーパークリークの名称が違う

### ISSUE THREAD

**Issue by trium-v** [amate/UmaUmaCruise#53]
UmaUmaCruiseバージョン：1.8

UmaumaCruise上では【マーマリンストーム】スーパークリークと表示されているクリークですが、
ゲーム内では「マーマリングストーム」が正しいようです。
![screenshot_1621365682](https://user-images.githubusercontent.com/83779447/118710984-fb246a80-b859-11eb-82d2-d5c1665f497a.png)

**Comment by amate** [comment]
・最新のUmaMusumeLibrary.jsonで修正済み
本体付属のはそのうち更新します
