### ISSUE TITLE
イベント名：掘り出し物

### ISSUE THREAD

**Issue by torinan** [amate/UmaUmaCruise#54]
いつもお世話になっています。
[こちらが無認識でしたのでご確認いただけれ幸いです。]
![screenshot_1621447280](https://user-images.githubusercontent.com/84470975/118862422-ad226c00-b918-11eb-8cc0-65da5674b2f0.png)

**Comment by amate** [comment]
こちらの環境ではちゃんと認識できてるように見えます
新しいバージョンに更新してみてください
