### ISSUE TITLE
新イベント無認識：花咲く、希望！

### ISSUE THREAD

**Issue by torinan** [amate/UmaUmaCruise#58]
サクラチヨノオーのイベントが無認識です
![screenshot_1622088394](https://user-images.githubusercontent.com/84470975/119764642-c31dc700-beec-11eb-8dc6-29e713e7f0a1.png)

**Comment by amate** [comment]
こちらの環境ではちゃんと認識できてるように見えます
新しいバージョンに更新してみてください
