### ISSUE TITLE
【要望】ステータスの上昇と下降を見やすくしてほしい

### ISSUE THREAD

**Issue by plannner** [amate/UmaUmaCruise#6]
+,-が半角で小さいため、視認性が悪いです。
上昇と下降の数値を色分けするなど、見やすくしてもらえるとありがたいです。

**Comment by amate** [comment]
ステータス協調は、リッチエディットに入力される日本語の表示がおかしいのを解決する方法が見つかるまで見送り

効果エディットウィンドウの幅を可変にするのは、実装が面倒なので別な方法で代用予定（マウスオーバーでポップアップさせるとか？）

**Comment by amate** [comment]
v1.9で対応しました
