### ISSUE TITLE
イベント効果量文字列が更新されなくなるケースがある。

### ISSUE THREAD

**Issue by akiregunomi** [amate/UmaUmaCruise#60]
サクラチヨノオーのイベント３段階目「花咲く、いつか！」の後、選択肢の結果（効果量）のテキストの更新が止まりました。
アプリケーションを落として、再起動することでもとに戻りました。
同じイベントかはちょっと自信が無いですが、過去にも１度発生しています。
ご確認いただけますでしょうか。
添付画像はクリークの夜の甘い誘惑（選択肢↑は体力３０回復 （確率で太り過ぎ））のイベントです。
![image](https://user-images.githubusercontent.com/85046157/120090648-1b4c0780-c13f-11eb-82ed-434e0802a405.png)

**Comment by amate** [comment]
v1.10で修正しました
