### ISSUE TITLE
ウイニングチケットのイベント[よく泣くお姉ちゃん]で選択肢の順序が異なる

### ISSUE THREAD

**Issue by horimkin** [amate/UmaUmaCruise#61]
選択肢が上下逆になっています。
元のサイトから間違っているので対応できないかもしれませんが報告しておきます

【Go To Winning!】ウイニングチケット
イベント名：よく泣くお姉ちゃん
- 正

|||
|-|-|
| 下手に動かず、待ち続けよう | 根性+5<br>スキルPt+15 |
| 辺りを見渡せる場所があるといいんだけど	 | やる気+1<br>パワー+5 |

- 誤
![2021-06-02 (4)](https://user-images.githubusercontent.com/26651273/120430359-dbd92180-c3b1-11eb-8e52-ae75d901e4b1.png)

- ゲームのスクリーンショット
![2021-06-02 (5)](https://user-images.githubusercontent.com/26651273/120430374-e1cf0280-c3b1-11eb-86d8-7c837066ae6c.png)

- 元サイト
![image](https://user-images.githubusercontent.com/26651273/120430425-f6ab9600-c3b1-11eb-9389-3241cf80256d.png)

イベント名：全力がんばる！
- 正

|||
|-|-|
| ライバルたちも同じ気持ちだろうね | スピード+10<br>賢さ+10<br>ランダムで「注目株」 |
| その感動を力に変えよう | パワー+20<br>ランダムで「注目株」 |

- 誤
![2021-06-02 (7)](https://user-images.githubusercontent.com/26651273/120435735-12666a80-c3b9-11eb-95d8-14e41853afc9.png)

- ゲームのスクリーンショット
![2021-06-02 (6)](https://user-images.githubusercontent.com/26651273/120435363-966c2280-c3b8-11eb-8e7c-34564e24ac34.png)

- 元サイト
![image](https://user-images.githubusercontent.com/26651273/120435900-3c1f9180-c3b9-11eb-806a-fe4bd7f42076.png)

**Comment by amate** [comment]
UmaMusumeLibrary.json更新で対応しました
v1.8は4択選択肢に対応していないので、そのままjsonだけを更新すると正常に動作しません
v1.9以降のバージョンに更新してください

**Comment by horimkin** [comment]
すみません、issue登録後、イベント名：全力がんばる！　においても同様に順序が逆だったので追記したのですが、タイトルの変更をし損なっていました。
二度手間となって申し訳ないですが、こちらの対応もお願いいたします。<(_ _)>

**Comment by amate** [comment]
修正しました
