### ISSUE TITLE
イベント誤認識「輝き、追いかけて」

### ISSUE THREAD

**Issue by user12023984** [amate/UmaUmaCruise#62]
![image](https://user-images.githubusercontent.com/85244059/120508880-0d2e0d80-c403-11eb-948c-7ad03b8970d2.png)
[迫る熱に押されて]キタサンブラックの「輝き、追いかけて」を[むじゃむじゃむじゃき]ナイスネイチャの「背、追いかけて」と誤認識しているようです

**Comment by amate** [comment]
既知の問題です　#25
実害がないので修正はしません
