### ISSUE TITLE
イベント誤認識　エルコンドルパサー「レース敗北」

### ISSUE THREAD

**Issue by Tyama-rmc4** [amate/UmaUmaCruise#66]
![image](https://user-images.githubusercontent.com/15401208/124318440-9f1c6800-dbb3-11eb-9b5c-d44756a19694.png)

他画面への切り替え時に、一時的に正確な選択肢が表示されるタイミング有り

**Comment by saia00** [comment]
同様の誤認識なのですが、『いつもの調子はどうした？』を隠すとエルコンドルパサーのイベントと認識するようです。
![20210720212730](https://user-images.githubusercontent.com/84856405/126324151-276459ea-f4b5-42b2-beda-476c181f3ea3.png)
![20210720212818](https://user-images.githubusercontent.com/84856405/126324165-2515410d-6727-4def-91d8-b692edf83085.png)

**Comment by amate** [comment]
v1.13で修正しました
