### ISSUE TITLE
【要望】 育成ウマ娘のソート

### ISSUE THREAD

**Issue by ryucchin** [amate/UmaUmaCruise#67]
手動で育成ウマ娘を設定する際に現在の状態だと、とても分かりづらいです
特に☆3ウマ娘は数が多く探すのに手間取ってしまいます

原因は育成ウマ娘の二つ名が頭に来ていることで二つ名でソートされてしまっているからだと思います
二つ名の長さが統一されている訳でもないので、名前の始まりの位置もバラバラで視認性が悪いです

そして、現在たまたまメジロマックイーンやトウカイテイオーは並んで表示されていますが
今後の実装されるウマ娘の二つ名次第では位置がバラバラになってしまいます

二つ名をウマ娘の名前の後ろに設定することでウマ娘の名前でソート出来るようにはならないでしょうか

![NNC29i4TvA](https://user-images.githubusercontent.com/87357302/125404323-76854100-e3f1-11eb-91a7-1a4582f11e07.png)

**Comment by amate** [comment]
育成ウマ娘の自動選択機能で充分なのと
二つ名で昇順ソートされているので、そっちで索引してもらえばいいと思うので
実装は保留で

**Comment by ryucchin** [comment]
返答ありがとうございます

ウマ娘は育成にそれなりに時間が掛かるので、スマートフォンで育成した続きをPCでやるなど
私の場合1育成を何回かに分けることが多くありました
そのため、手動で設定する場面があり、もう少し分かりやすくならないかなと思って提案させて貰いました

保留とのことで、変更をするかどうか決まり次第Closeしてもらって大丈夫です

**Comment by mayopon** [comment]
チケットの便乗失礼します。

以前オミットした、能力詳細画面での自動認識をスタートボタンを押したときに限って行う、というのはいかがでしょうか？
プログラムが必要以上に複雑になるようであればスルーしてください。

**Comment by mayopon** [comment]
issue のタイトルとかけ離れた内容だったので、別のissueを作成しました #70

**Comment by amate** [comment]
v1.13で、スタート押したとき一度だけ、能力詳細から育成ウマ娘名を取得する処理を入れました
