### ISSUE TITLE
レース一覧の育成目標に関する機能案

### ISSUE THREAD

**Issue by AkemiYuzuki** [amate/UmaUmaCruise#68]
レース一覧において、育成目標に関するいくつかの機能を追加してほしいです。
・目標レースと着順の表示
既存のレース予約機能とは別に、育成ウマ娘から自動的に設定されてほしい。
レース名の欄で「G1 高松宮記念 (目標：1着)」「G1 安田記念(目標：3着)」とか。

・目標レースと被るレースの非表示
上記と合わせ、育成目標と被るレースにはどうせ出られないので、
いっそ表示されない方が一覧の表示が減って見やすくなるのでは、と思います。

あとこれは育成目標関係ないですが、月の変わり目等で枠線を太くすることはできませんか？
ご検討の程よろしくお願いします。

**Comment by amate** [comment]
＞・目標レースと着順の表示
キャラ毎の出走レースのメタデータを取得するのが大変＆キャラによっては出るレースが変わる場合があるので実装はしません

＞・目標レースと被るレースの非表示
上記機能は実装しないのでナシで

＞月の変わり目等で枠線を太く
標準のListViewではおそらく無理そう
現在の実装である日付変わりで背景色変えるだけで許してください
