### ISSUE TITLE
【要望】育成ウマ娘の自動選択機能の精度向上、もしくはONOFF切り替えの実装

### ISSUE THREAD

**Issue by nananagi** [amate/UmaUmaCruise#69]
同じウマ娘を連続して育成する際に、2週目の育成を選択して、継承の親を選択する画面で因子を確認しながら選んでいると、育成ウマ娘が変わってしまうので、継承ウマ娘選択時に変更にならないようにするか、自動選択機能のOFF機能が欲しいです。

例：ウオツカを選択して育成完了後、ウオツカの育成を再度開始しようとして継承ウマ娘を吟味し始めると、UmaUmaCruiseの育成ウマ娘の選択がウオツカから継承ウマ娘側に変わってしまう

**Comment by amate** [comment]
最新バージョンでは、育成ウマ娘選択画面に表示されているウマ娘名を利用して自動選択しているので、アップデートしてください
