### ISSUE TITLE
【要望】スタートボタンを押した際に、能力詳細画面での育成ウマ娘自動認識をして欲しい

### ISSUE THREAD

**Issue by mayopon** [amate/UmaUmaCruise#70]
ウマウマクルーズのスタートボタンを押した際に、以前オミットした、
能力詳細画面での育成ウマ娘の自動認識を行ってもらえませんでしょうか？

育成開始後にウマウマクルーズを起動していなかったことに気付いた場合などに、ウマ娘選択を楽にするのが目的です。

メジロマックイーンやトウカイテイオーなどは新旧衣装がたまたまリスト内で隣同士、しかも旧が上になっているので見分けがつきやすいですが、今後ウマ娘や衣装が増えてくると、何かしらの機能が欲しくなってくると思います。
別アイデアで目的が達成されるなら、上で挙げた機能自体にこだわりはないです。

**Comment by amate** [comment]
v1.13で実装しました
