### ISSUE TITLE
Does not create UmeUmaCruise.Exe or can not locate?

### ISSUE THREAD

**Issue by Val076** [amate/UmaUmaCruise#71]
Ran sln through and did not finish; please help or advise.

**Comment by amate** [comment]
What did visual studio show you after the build?
Did you follow the "How to build" instructions in readme.md?

**Comment by Val076** [comment]
Will do a "out of the box" Build per instructions and attach Install log if goes bust.

**Comment by Val076** [comment]
Second time is the Charm, thank you again!!!!
