### ISSUE TITLE
【要望】育成ウマ娘のドロップダウンリストを見やすくしてほしい

### ISSUE THREAD

**Issue by plannner** [amate/UmaUmaCruise#73]
[要望]
育成ウマ娘を選択する際に展開されるドロップダウンリストの視認性を上げてほしいです。
現在は、ウマ娘の名前の位置がバラバラであるため、探すのがちょっと大変です。

[仕様の案]
説明とウマ娘の名前がそれぞれ左揃えされて表示されるようにするのはいかがでしょうか。

【マーマリングストリーム】スーパークリーク
【岩穿つ青】グラスワンダー

　　↓

【マーマリングストリーム】スーパークリーク
【岩穿つ青】　　　　　　　グラスワンダー

**Comment by amate** [comment]
プロポーシャルフォントで表示される都合上、幅を合わせるのが難しいので見送りで
v1.13で、スタート押したとき一度だけ、能力詳細から育成ウマ娘名を取得する処理を入れたので困ることはないでしょう
