### ISSUE TITLE
【要望】目標・予約レースに対し「あとXターン」を表示して欲しい

### ISSUE THREAD

**Issue by u2317** [amate/UmaUmaCruise#74]
予約レースの当日通知について，現状の音＋振動通知だと，通知があったということを一瞬でも記憶に留めないといけないのでちょっとつらいです．（ながらプレイをしているとちょくちょく出走を忘れます・・・）
なので，できれば行動選択時にひと目で予約レース日かどうかが判断できるようになっているとありがたく，どうせなら「あとXターン/本番」形式だと体力管理にも活用しやすいかと思います．

ご検討をお願い致します．

**Comment by amate** [comment]
v1.14で実装しました
