### ISSUE TITLE
イベント「温もり愛情弁当」が認識されない

### ISSUE THREAD

**Issue by niratama** [amate/UmaUmaCruise#8]
ニシノフラワーのサポートカードイベント「温もり愛情弁当」が認識されませんでした

![210420_122631](https://user-images.githubusercontent.com/141543/115337456-fbd6cc00-a1db-11eb-95a5-167f80d3ebe6.png)

Aboutダイアログのdebug機能でのOCR結果でも誤認識されているようです。しばらく放置しているとごくたまに正常に認識されることもあります。

![210420_122703](https://user-images.githubusercontent.com/141543/115337514-13ae5000-a1dc-11eb-8c1e-7ef388422c0e.png)

**Comment by amate** [comment]
v1.3で修正されたはずです
もし直ってなかったらまたissueを立ててください
その場合は、本体の"スクリーンショット"で保存した画像を上げてもらえると助かります
