### ISSUE TITLE
v1.15より、複数画面時にウマ娘のウィンドウを認識しない場合がある

### ISSUE THREAD

**Issue by kurohach** [amate/UmaUmaCruise#80]
これまでv1.14を使用しており、v1.15.2に更新した際に認識しなくなりました。
なるべくトラブルシューティングをしたのですが、v1.15での処理方法の変更によるものだと思われるため、
issueとして報告します。

以下、なるべく具体的な環境及び、具体的な症状を明記します。
まず、ディスプレイの配置がこちらになります。
![image](https://user-images.githubusercontent.com/92240548/136681476-d689a8d8-fbc2-49c0-9369-369282e00431.png)
それぞれのディスプレイの解像度は、
Display1: 1920x1080
Display2: 1600x900
Display3: 1080x1920
です。
起点は、Display1の左上になっているようです。

主なマシンスペックは以下の通りです。
CPU: Xeon E3-1240v5
GPU1: RadeonVII (DriverVersion: 21.6.1)
GPU2: GT730 (DriverVersion: 466.47)
RAM: DDR4-2133 48GB
M/B: GA-X170-WS ECC
上記のスペックで、特にスペック不足による問題は起きにくいかと思います。

また、複数のグラフィックボードを搭載しており、それぞれの画面出力は、
Display1: RadeonVII
Display2&3: GT730
となっております。

今回の具体的な症状ですが、
Display1にウマ娘のウィンドウがある際には問題なく取得できております。
![image](https://user-images.githubusercontent.com/92240548/136681769-d126f66e-3dee-475d-ae72-f86384400ebe.png)
![image](https://user-images.githubusercontent.com/92240548/136681780-cdab07b2-f9a9-453e-aad2-f787b3582d63.png)

ですが、Display2及び、Display3にウィンドウを移動した際に、
v1.15からは取得できなくなっております。
![image](https://user-images.githubusercontent.com/92240548/136681809-0124bea1-03b3-4e62-9d16-d61336570024.png)
![image](https://user-images.githubusercontent.com/92240548/136681822-4beaaaaa-3c3d-463e-811b-bf263e06476c.png)

いずれのバージョンも管理者権限での起動及び、ダウンロード時のブロック解除もしておりますが、改善しません。
また、ディレクトリをD:直下においてもダメでした。
パソコンを再起動してもダメです。

ちなみに、画面の境目にウマ娘のウィンドウを配置した場合、少し切れている程度であれば拾うようですが、
半分程度かそれ以上切れた場合は拾わないようです。
よって、Display1の全体はしっかりと拾えるようですが、Display2及び3に移動した際には拾えないです。

画面の配置を見ての通り、Display3の縦画面で普段プレイしているので、この画面で拾えないのはかなり不便です。
できれば修正お願い致します。
また、これら以外にも必要な情報があれば基本的に答えますので、その際はコメントもしくは下記Twitterにお願いします。
Twitter: @kuro23112

追記:Display2を変換噛ませてDisplay1と同じRadeonVIIに接続し、ウマ娘のウィンドウをDisplay2に移動した所、v1.15以降も拾えました。GT730に接続しているDisplay3はダメでした。
つまり、どうやらグラボを超えると拾えないようです。
もしくは、GeforceとRadeonの違いもあるかもしれません。
ドライバのバージョンや相性の可能性もあるかもしれませんが、
試すごとにOSにダメージを与える可能性があり、そしてバージョンの数が膨大なので試しておりません。

**Comment by amate** [comment]
[UmaUmaCruise_1.15.3.zip](https://github.com/amate/UmaUmaCruise/files/7316986/UmaUmaCruise_1.15.3.zip)
複数グラボに対応させたので、これを試してみてください

**Comment by kurohach** [comment]
迅速な対応ありがとうございます。

無事動作し、しっかり検出出来ていました。
![image](https://user-images.githubusercontent.com/92240548/136693171-1c5a3c64-f556-40b0-9ca5-8cf9b3cb4d57.png)

修正ありがとうございます。
