### ISSUE TITLE
Assertion failed!と警告が表示され強制終了してしまう。

### ISSUE THREAD

**Issue by kei527** [amate/UmaUmaCruise#84]
![スクリーンショット (685)](https://user-images.githubusercontent.com/52921251/139563385-3d92609c-8da3-427f-ade5-16596606717c.png)

windows 10 64bit

キングヘイローを選択すると確実に発生し、再試行、無視を選択してもクラッシュします。
おそらく私のデバックの仕方に問題があるのだと思うのですが
手順通りに行ったので何が原因なのかわかりません。

**Comment by amate** [comment]
その画面だけを見せられても分かりません
呼び出し履歴を見て、どの関数が問題になっているか把握してください
なぜ落ちるのかは assertion に書いてあります
存在しないjson keyを指定したため落ちたと推測できます
であれば、なぜ 当然あるべき情報がない状態になったのかをコードを追って調べることができます
