### ISSUE TITLE
【秋桜ダンツァトリーチェ】ゴールドシチー　イベント：初詣　読み取り失敗

### ISSUE THREAD

**Issue by L-SMK** [amate/UmaUmaCruise#86]
![screenshot_1636281753](https://user-images.githubusercontent.com/26026130/140641694-3c02dcb2-17ba-46eb-a769-f5699ae0d9e4.png)

![image](https://user-images.githubusercontent.com/26026130/140641728-663be849-a799-468d-b1bc-a4a27f2e3f67.png)

**Comment by amate** [comment]
v1.17で修正しました
