### ISSUE TITLE
win7でのエラー

### ISSUE THREAD

**Issue by sora0615** [amate/UmaUmaCruise#87]
日文苦手
OS:WIN7
VER1.14:OK
VER1.15以降:NOT OK

![1636901793178](https://user-images.githubusercontent.com/94304271/141686408-91617320-380f-4270-930e-a7d345ea7c0c.jpg)
)

下記內容 機械翻訳
UmaUmaCruise.exe-入力ポイントが見つかりません

プログラム入力ポイントColncrementMTAUsageが見つかりません（ダイナミックリンクライブラリ内）
ole32.dll）。

**Comment by konomn** [comment]
![image](https://user-images.githubusercontent.com/95279641/144019611-442dd166-c891-4462-89d3-51c2a66d08bd.png)

**Comment by amate** [comment]
v1.18で修正しました
