### ISSUE TITLE
[要望] 必ず出走するレースがわかると嬉しい

### ISSUE THREAD

**Issue by airflow2k** [amate/UmaUmaCruise#88]
大変便利に使わせていただいております。

育成するウマ娘ごとに出走できるレースは異なりますが、
レース一覧でそのウマ娘が必ず出走するレースがわかるとありがたいです。
もう少し欲を言うと、裏レースは出られないので、レース予約で選べないようになると嬉しいです。

**Comment by amate** [comment]
キャラによっては、どのレースに出走するか分岐するパターンがあるので、予め登録しておくことはしません

自分は育成中に必ず出走するレースをお気に入り登録することで充分だと考えています
最初に１回やればいいだけですし

**Comment by airflow2k** [comment]
わかりました！お忙しい中ご返信ありがとうございました
