### ISSUE TITLE
[要望]育成ウマ娘の順番の変更

### ISSUE THREAD

**Issue by daikiclimate** [amate/UmaUmaCruise#89]
育成ウマ娘の一覧の順番を変更、もしくは変更可能な状態にしてほしいです。
現状は二つ名？敬称でソートされています。【】のことです。

ゲームの公開から時間が経つにつれ☆３ウマ娘は増え続けています。
そこでキャラクターを探すのが面倒になるともに、同じキャラクター(マルゼンスキーと水着マルゼンスキー)が遠くにいることに違和感を感じます。

ベースをキャラクター名でソート、あるいはソート可能な状態にしていただけないでしょうか？

**Comment by amate** [comment]
育成ウマ娘の自動選択機能で充分なので実装しません
