### ISSUE TITLE
[bug]マヤノトップガン：「甘いキモチをキミに♪」が認識されない

### ISSUE THREAD

**Issue by minokich** [amate/UmaUmaCruise#9]
![image](https://user-images.githubusercontent.com/40020414/115391058-fc8e5300-a219-11eb-82e5-77522fe5ae17.png)

**Comment by amate** [comment]
v1.3で修正されたはずです
もし直ってなかったらまたissueを立ててください
その場合は、本体の"スクリーンショット"で保存した画像を上げてもらえると助かります
