### ISSUE TITLE
イベントの誤認識

### ISSUE THREAD

**Issue by gamu239** [amate/UmaUmaCruise#90]
［43、8、1］ナカヤマフェスタのサポートカードの
育成イベント予兆の夜が
［トレセン学園］スイープトウショウの
ミラクル☆エスケープ！と認識されるので
修正お願いしたいです
![screenshot_1639500992](https://user-images.githubusercontent.com/96137483/146045434-8211b155-b52d-4b1d-9620-29adb0176850.png)

**Comment by yousuke2** [comment]
ゲーム側の選択肢とumaumacruise側の選択肢が異なっていましたので報告いたします。
![screenshot_1640621124](https://user-images.githubusercontent.com/96739271/147488904-7c8588d7-d7cf-41f8-9e82-7e573eca13f2.png)

**Comment by amate** [comment]
> ［43、8、1］ナカヤマフェスタのサポートカードの 育成イベント予兆の夜が ［トレセン学園］スイープトウショウの ミラクル☆エスケープ！と認識されるので 修正お願いしたいです

v1.18で修正しました

> ゲーム側の選択肢とumaumacruise側の選択肢が異なっていましたので報告いたします。

選択肢の表示が異なるのは、トレーナーの性別の違いによるものです

**Comment by gamu239** [comment]
> v1.18で修正しました

ありがとうございます
