### ISSUE TITLE
要望：育成ウマ娘選択の表示について

### ISSUE THREAD

**Issue by 22202207** [amate/UmaUmaCruise#91]
いつも大変快適なウマ娘ライフをありがとうございます。

現在
【疾風迅雷】タマモクロス
という表示になっていると思うのですが

タマモクロス【疾風迅雷】
という表示に変更できるようにしていただけたら大変うれしいです。
上の場合　疾風迅雷（し）　でA-Z順になっているため同キャラでもかなり離れている事があり　どっちの名前だっけ？となる場合が度々あります。
同キャラが近くに並んでいると探しやすいなと思い記入いたしました。

プログラミング未経験のため無茶な要望をもし言っていたらすみません。
負担にならない場合はぜひ検討をお願いします。
少しでも負担になってしまう場合は気にしませんので、むしろこんなに良いツールを使わせてもらって感謝しています。

**Comment by amate** [comment]
#89 の通り今のところ実装する予定はありません
どうしてもというなら、自身で UmaMusumeLibrary.json を編集して、二つ名とウマ娘名の場所を置換してください

**Comment by 22202207** [comment]
過去に提案があったのですね。
すみません気がついていませんでした。
ありがとうございますjsonを勉強して自分で編集してみます！
教えてくださりありがとうございます。
