### ISSUE TITLE
[要望]育成ウマ娘のソートについて

### ISSUE THREAD

**Issue by YaoFeilung** [amate/UmaUmaCruise#92]
新年明けましておめでとうございます。
いつもウマ娘育成で本ツールを使わせて頂いています。
1つ要望なのですが、育成ウマ娘が増えて同じキャラでも衣装違いも出て来たので現在のソートから探しにくく思っています。
可能であれば、ソートの第1優先を本来のウマの名前でも可能にして欲しいです。
人により今のままが良いという場合もあるので、設定による変更などでも良いかと思います。

例
「【エンド・オブ・スカイ】メジロマックイーン」の場合、「メジロマックイーン」→「エンド・オブ・スカイ」の優先順位でソートされる。

ご検討をよろしくお願いします。

あと、ついでですが、☆の数も関係無くソート出来ると探しやすい気もするので、合わせてご検討をよろしくお願いします。

**Comment by amate** [comment]
#91
