### ISSUE TITLE
イベント誤認識：夕陽にときめいて

### ISSUE THREAD

**Issue by ossan-pg** [amate/UmaUmaCruise#93]
メジロドーベルのお出かけイベント「夕陽にときめいて」がSSRダイタクヘリオスの「太陽とエンカウント☆」に誤認識されます。

![image](https://user-images.githubusercontent.com/7059614/151149979-3074b90f-0e29-4ae0-b310-8e9556f6457d.png)

**Comment by amate** [comment]
修正しました
本体の"設定"から"UmaMusumeLibrary.jsonの更新確認"を実行してください
