### ISSUE TITLE
樫本理子(SSR) イベント：意外な一面 

### ISSUE THREAD

**Issue by Kaiay** [amate/UmaUmaCruise#94]
![image](https://user-images.githubusercontent.com/43386053/151584611-7c3bda51-c441-4629-be66-a4b52d353e58.png)
下の二つが表示されない
調べるとGamerchサイトの下の二つが何もないままなのでどうしようもないかも
![image](https://user-images.githubusercontent.com/43386053/151585576-b9d5654f-86a2-4c96-938f-5e62ec9be2ab.png)
参考資料︰https://gamewith.jp/uma-musume/article/show/292758

**Comment by amate** [comment]
修正しました
本体の"設定"から"UmaMusumeLibrary.jsonの更新確認"を実行してください
