### ISSUE TITLE
要望：「育成ウマ娘」リストのソート順について

### ISSUE THREAD

**Issue by masakaj** [amate/UmaUmaCruise#95]
新衣装キャラが登場した際、新選択肢に対応した設定ファイルが登場するまでの間は暫定的に旧キャラで代用する事でどうにか回してますが、正直今の順序では見つけるのが困難です。
キャラ名50音順でのリストになっているのが直感的に分かりやすいと思いますので第1ソートキーはキャラ名で、そして各衣装の登場順が第2ソートキーとなるような、そんなソート順をご検討よろしくお願いします。

**Comment by amate** [comment]
#91
